namespace GeneralsCombiner;

public static class Constants
{
    /// <summary>
    /// Multi-version support
    /// </summary>
    public static readonly string[] VersionDependent = [".h", ".cpp", ".c"];

    /// <summary>
    /// Keep both
    /// </summary>
    public static readonly string[] OldProjectFiles = [".dsp", ".dsw"];

    /// <summary>
    /// Should be duplicated OR merge manually
    /// </summary>
    public static readonly string[] ProjectFiles = [".sln", ".vcxproj"];

    /// <summary>
    /// Requires manual merging
    /// </summary>
    public static readonly string[] MergedManually = [".gitignore", ".bmp", ".ico", ".RC", ".txt", ".odl", ".hm", ".idl", ".vsh", ".psh"];

    /// <summary>
    /// Ignored at merge
    /// </summary>
    public static readonly string[] AutoGeneratedIgnored = [".vcxproj.filters", "v12.suo", ".htm"];

    /// <summary>
    /// No modifications needed, keep first version
    /// </summary>
    public static readonly string[] OriginalUnchanged = [".inl", ".nvp", ".nvv", ".PL"];

    public static readonly string[] CheckedFilesExtensions =
        [.. VersionDependent, .. OldProjectFiles, .. ProjectFiles,
        .. MergedManually, .. AutoGeneratedIgnored, .. OriginalUnchanged];
}
